In [5]:
import tensorflow as tf

x_data = [[1,2,1], [1,3,2], [1,3,4], [1,5,5], [1,7,5], [1,2,5], [1,6,6], [1,7,7]]
y_data = [[0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0], [1,0,0], [1,0,0]]

# Evaluation our model using this test dataset
x_test = [[2,1,1], [3,1,2], [3,3,4]]
y_test = [[0,0,1], [0,0,1], [0,0,1]]

X = tf.placeholder(tf.float32, [None, 3])
Y = tf.placeholder(tf.float32, [None, 3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
        
    print('Prediction: ', sess.run(prediction, feed_dict={X: x_test}))
    print('accuracy: ', sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 9.256844 [[-0.21815145 -1.6343436  -0.53386015]
 [-1.1850698  -0.10334627  1.021663  ]
 [-0.26422954  0.3212008  -0.07463422]]
1 5.6234646 [[-0.19345577 -1.5996616  -0.5932379 ]
 [-1.0232091   0.06496085  0.6914952 ]
 [-0.1024138   0.49709225 -0.4123414 ]]
2 2.8218865 [[-0.17015634 -1.6085134  -0.6076855 ]
 [-0.8645542   0.03521004  0.5625911 ]
 [ 0.05573224  0.45086214 -0.5242573 ]]
3 2.066823 [[-0.15069762 -1.6291862  -0.6064714 ]
 [-0.7154239  -0.06463829  0.51330906]
 [ 0.20106909  0.3421994  -0.56093144]]
4 1.4779084 [[-0.14307283 -1.631915   -0.6113674 ]
 [-0.60124254 -0.08675471  0.42124414]
 [ 0.29783922  0.3216759  -0.63717806]]
5 1.2253885 [[-0.15220232 -1.6332827  -0.60087025]
 [-0.55514777 -0.11590834  0.404303  ]
 [ 0.32087824  0.30564    -0.6441812 ]]
6 1.2017283 [[-0.16954398 -1.6277153  -0.58909583]
 [-0.54971343 -0.10904783  0.3920082 ]
 [ 0.3026729   0.3265674  -0.6469032 ]]
7 1.1879172 [[-0.18350966 -1.6266024  -0.57624316]
 [-0.5283866  -0.12544219  0.38707566]
 [

158 0.65909886 [[-1.4779853  -1.4754678   0.56709826]
 [ 0.03447385 -0.16138083 -0.13984579]
 [ 0.24653453  0.32214603 -0.586343  ]]
159 0.6580316 [[-1.4833317  -1.4747376   0.57171446]
 [ 0.0350773  -0.160879   -0.14095107]
 [ 0.24803151  0.3215805  -0.58727443]]
160 0.6569724 [[-1.4886589  -1.474007    0.576311  ]
 [ 0.0356711  -0.16038194 -0.1420419 ]
 [ 0.24953026  0.32101908 -0.5882117 ]]
161 0.6559213 [[-1.493967   -1.4732759   0.58088803]
 [ 0.03625549 -0.15988971 -0.14311853]
 [ 0.25103077  0.3204616  -0.5891547 ]]
162 0.6548781 [[-1.4992565  -1.4725443   0.5854458 ]
 [ 0.03683051 -0.15940215 -0.14418113]
 [ 0.25253284  0.31990808 -0.59010327]]
163 0.6538427 [[-1.5045273  -1.4718122   0.58998454]
 [ 0.03739649 -0.1589193  -0.14522995]
 [ 0.25403655  0.31935835 -0.59105724]]
164 0.652815 [[-1.5097798  -1.4710797   0.5945044 ]
 [ 0.03795338 -0.15844096 -0.1462652 ]
 [ 0.25554162  0.31881246 -0.59201646]]
165 0.65179485 [[-1.515014   -1.4703467   0.59900564]
 [ 0.03850154 -0.15796