In [16]:
import tensorflow as tf
import numpy as np

def MinMaxScaler(data):    
    numerator = data - np.min(data, 0)
    #print('numerator: \n', numerator)
    denominator = np.max(data, 0) - np.min(data, 0)
    #print('denominator: ', denominator)
    return numerator / (denominator + 1e-7)

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973], # maximum
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]]) #minimun
xy = MinMaxScaler(xy)
print('MinMaxScaler:\n', xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]))
b = tf.Variable(tf.random_normal([1]))

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

MinMaxScaler:
 [[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
0 Cost:  9.685629 
Prediction:
 [[-3.5966861]
 [-3.9764173]
 [-2.8388734]
 [-1.5662568]
 [-2.316445 ]
 [-2.2191932]
 [-0.8195483]
 [-1.0145953]]
1 Cost:  9.684917 
Prediction:
 [[-3.5965288]
 [-3.976266 ]
 [-2.8387477]
 [-1.5661606]
 [-2.3163302]
 [-2.2190824]
 [-0.8194757]
 [-1.0145243]]
2 Cost:  9.684206 
Prediction:
 [[-3.596372 ]
 [-3.9761145]
 [-2.8386223]
 [-1.5660641]
 [-2.3162153]
 [-2.218972 ]
 [-0.8194032]
 [-1.0144532]]
3 Cost:  9.683495 
Prediction:
 [[-3.5962148 ]
 [-3.9759629 ]
 [-2.8384964 ]
 [-1.565

74 Cost:  9.633144 
Prediction:
 [[-3.585075  ]
 [-3.965222  ]
 [-2.8295937 ]
 [-1.5591383 ]
 [-2.3079536 ]
 [-2.2110023 ]
 [-0.81418735]
 [-1.0093426 ]]
75 Cost:  9.632437 
Prediction:
 [[-3.5849183]
 [-3.965071 ]
 [-2.8294685]
 [-1.5590422]
 [-2.3078392]
 [-2.210892 ]
 [-0.8141151]
 [-1.0092717]]
76 Cost:  9.631731 
Prediction:
 [[-3.5847619]
 [-3.96492  ]
 [-2.8293433]
 [-1.5589463]
 [-2.3077247]
 [-2.2107816]
 [-0.8140427]
 [-1.0092008]]
77 Cost:  9.631024 
Prediction:
 [[-3.5846052 ]
 [-3.9647691 ]
 [-2.8292181 ]
 [-1.5588503 ]
 [-2.30761   ]
 [-2.2106712 ]
 [-0.81397045]
 [-1.00913   ]]
78 Cost:  9.630317 
Prediction:
 [[-3.5844483]
 [-3.9646182]
 [-2.829093 ]
 [-1.5587542]
 [-2.3074956]
 [-2.2105603]
 [-0.8138981]
 [-1.0090592]]
79 Cost:  9.62961 
Prediction:
 [[-3.584292  ]
 [-3.9644668 ]
 [-2.8289678 ]
 [-1.5586582 ]
 [-2.307381  ]
 [-2.21045   ]
 [-0.81382585]
 [-1.0089884 ]]
80 Cost:  9.628902 
Prediction:
 [[-3.5841353 ]
 [-3.964316  ]
 [-2.8288426 ]
 [-1.5585623 ]
 [-2.307