In [16]:
import tensorflow as tf

x_data = [[73., 93., 89., 96., 73.],
          [80., 88., 91., 98., 66.],
          [75., 93., 90., 100., 70.]]
y_data = [[152.], 
          [185.], 
          [180.]]
# placeholder for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 5])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([5, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    c, h, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})    
    if step % 10 == 0:
        print(step, '\ncost: ', c, '\npredict: \n', h , '\n')


0 
cost:  25785.162 
predict: 
 [[18.195732]
 [11.244148]
 [ 8.942101]] 

10 
cost:  318.4695 
predict: 
 [[177.13144]
 [170.18251]
 [169.78915]] 

20 
cost:  316.46262 
predict: 
 [[177.05768]
 [170.26912]
 [169.77739]] 

30 
cost:  314.47305 
predict: 
 [[176.98396]
 [170.35507]
 [169.76541]] 

40 
cost:  312.5007 
predict: 
 [[176.91054]
 [170.44058]
 [169.75351]] 

50 
cost:  310.54547 
predict: 
 [[176.83745]
 [170.52573]
 [169.74168]] 

60 
cost:  308.60684 
predict: 
 [[176.76466]
 [170.61049]
 [169.72995]] 

70 
cost:  306.6854 
predict: 
 [[176.69218]
 [170.69482]
 [169.71826]] 

80 
cost:  304.78 
predict: 
 [[176.62004]
 [170.77884]
 [169.7067 ]] 

90 
cost:  302.89145 
predict: 
 [[176.54817]
 [170.8624 ]
 [169.69516]] 

100 
cost:  301.01935 
predict: 
 [[176.47664]
 [170.94559]
 [169.68372]] 

110 
cost:  299.16324 
predict: 
 [[176.40543]
 [171.02843]
 [169.67236]] 

120 
cost:  297.32312 
predict: 
 [[176.3345 ]
 [171.11087]
 [169.66107]] 

130 
cost:  295.49893 
predic

1280 
cost:  162.39754 
predict: 
 [[169.85625]
 [178.49315]
 [168.77467]] 

1290 
cost:  161.71118 
predict: 
 [[169.81305]
 [178.54105]
 [168.7701 ]] 

1300 
cost:  161.0307 
predict: 
 [[169.77002]
 [178.58871]
 [168.7655 ]] 

1310 
cost:  160.35559 
predict: 
 [[169.72719]
 [178.63618]
 [168.76099]] 

1320 
cost:  159.68564 
predict: 
 [[169.68454]
 [178.68346]
 [168.75655]] 

1330 
cost:  159.02124 
predict: 
 [[169.642  ]
 [178.73041]
 [168.75208]] 

1340 
cost:  158.36226 
predict: 
 [[169.59972]
 [178.77724]
 [168.74771]] 

1350 
cost:  157.70863 
predict: 
 [[169.55756]
 [178.82379]
 [168.74333]] 

1360 
cost:  157.05995 
predict: 
 [[169.51561]
 [178.8702 ]
 [168.73906]] 

1370 
cost:  156.41687 
predict: 
 [[169.47382]
 [178.9163 ]
 [168.73479]] 

1380 
cost:  155.779 
predict: 
 [[169.43222]
 [178.96225]
 [168.73056]] 

1390 
cost:  155.14594 
predict: 
 [[169.39078]
 [179.00797]
 [168.7264 ]] 

1400 
cost:  154.51816 
predict: 
 [[169.3495 ]
 [179.05345]
 [168.72224]] 

14