In [16]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

#print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    c, h, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, 'cost: ', c, '\nprediction\n', h)

(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
0 cost:  422.42456 
prediction
 [[177.68663 ]
 [203.55896 ]
 [205.96075 ]
 [221.65152 ]
 [154.91238 ]
 [108.8674  ]
 [164.7129  ]
 [120.742905]
 [184.63521 ]
 [164.20065 ]
 [158.43604 ]
 [150.76382 ]
 [215.3487  ]
 [182.12956 ]
 [163.67542 ]
 [204.94923 ]
 [173.57281 ]
 [198.34833 ]
 [207.26666 ]
 [186.03708 ]
 [192.69267 ]
 [188.99007 ]
 [185.32132 ]
 [185.15256 ]
 [213.80544 ]]
10 cost:  68.55605 
prediction
 [[160.10205]
 [182.4752 ]
 [185.15875]
 [199.01378]
 [138.8311 ]
 [ 97.0439 ]
 [147.77899]
 [108.20332]
 [164.96387]
 [146.02287]
 [142.11868]
 [134.70378]
 [193.84062]
 [164.22885]
 [146.67323]
 [183.56586]
 [156.51974]
 [178.025  ]
 [186.75113]
 [167.67813]
 [172.8362 ]
 [169.2242 ]
 [166.38046]
 [167.38393]
 [191.9384 ]]
20 cost:  67.98932 
prediction
 [[159.94814]
 [182

480 cost:  47.30661 
prediction
 [[158.5952 ]
 [182.82661]
 [184.33075]
 [198.84149]
 [139.03468]
 [ 98.57229]
 [148.1281 ]
 [109.06651]
 [166.68523]
 [149.42314]
 [142.35051]
 [136.16632]
 [192.27632]
 [162.03079]
 [147.42769]
 [184.41791]
 [154.2117 ]
 [178.4035 ]
 [184.8108 ]
 [165.84036]
 [173.29643]
 [170.12752]
 [166.428  ]
 [164.20547]
 [191.61949]]
490 cost:  46.944016 
prediction
 [[158.56885]
 [182.83603]
 [184.3177 ]
 [198.84125]
 [139.04057]
 [ 98.60296]
 [148.13713]
 [109.08488]
 [166.72063]
 [149.49043]
 [142.35713]
 [136.19632]
 [192.24928]
 [161.99113]
 [147.44444]
 [184.43698]
 [154.16975]
 [178.41362]
 [184.77647]
 [165.80774]
 [173.30797]
 [170.14735]
 [166.43152]
 [164.14717]
 [191.61624]]
500 cost:  46.58464 
prediction
 [[158.5426  ]
 [182.84541 ]
 [184.30472 ]
 [198.84099 ]
 [139.04643 ]
 [ 98.633484]
 [148.14612 ]
 [109.10317 ]
 [166.75584 ]
 [149.5574  ]
 [142.36371 ]
 [136.22621 ]
 [192.22237 ]
 [161.95166 ]
 [147.46112 ]
 [184.45595 ]
 [154.12799 ]
 [178.4237

810 cost:  36.885075 
prediction
 [[157.7859 ]
 [183.11455]
 [183.92957]
 [198.83429]
 [139.21304]
 [ 99.51411]
 [148.40802]
 [109.63562]
 [167.77179]
 [151.49217]
 [142.55466]
 [137.08865]
 [191.44405]
 [160.8092 ]
 [147.94476]
 [185.00319]
 [152.91776]
 [178.71869]
 [183.75485]
 [164.83711]
 [173.65274]
 [170.73643]
 [166.53835]
 [162.41164]
 [191.5176 ]]
820 cost:  36.614357 
prediction
 [[157.76321 ]
 [183.12257 ]
 [183.9183  ]
 [198.8341  ]
 [139.21796 ]
 [ 99.540504]
 [148.41594 ]
 [109.65174 ]
 [167.80223 ]
 [151.55022 ]
 [142.5604  ]
 [137.11452 ]
 [191.42065 ]
 [160.77486 ]
 [147.95932 ]
 [185.01959 ]
 [152.8813  ]
 [178.72765 ]
 [183.72522 ]
 [164.80894 ]
 [173.66281 ]
 [170.7535  ]
 [166.54149 ]
 [162.36128 ]
 [191.51468 ]]
830 cost:  36.34601 
prediction
 [[157.74065 ]
 [183.13055 ]
 [183.90709 ]
 [198.83392 ]
 [139.22284 ]
 [ 99.56677 ]
 [148.42384 ]
 [109.667786]
 [167.83255 ]
 [151.60802 ]
 [142.56612 ]
 [137.14026 ]
 [191.39737 ]
 [160.74066 ]
 [147.97383 ]
 [185.03592 

1120 cost:  29.513706 
prediction
 [[157.12918]
 [183.34598]
 [183.60278]
 [198.82947]
 [139.35353]
 [100.27863]
 [148.64003]
 [110.10688]
 [168.65378]
 [153.17635]
 [142.72194]
 [137.8386 ]
 [190.76494]
 [159.8113 ]
 [148.36914]
 [185.47832]
 [151.85785]
 [178.98232]
 [182.89444]
 [164.02046]
 [173.94644]
 [171.23088]
 [166.63176]
 [160.95033]
 [191.43184]]
1130 cost:  29.30794 
prediction
 [[157.1095  ]
 [183.35286 ]
 [183.59297 ]
 [198.82932 ]
 [139.35767 ]
 [100.30152 ]
 [148.64705 ]
 [110.121124]
 [168.68019 ]
 [153.22687 ]
 [142.72696 ]
 [137.86108 ]
 [190.74452 ]
 [159.78128 ]
 [148.38194 ]
 [185.49255 ]
 [151.82593 ]
 [178.99034 ]
 [182.86858 ]
 [163.99596 ]
 [173.95532 ]
 [171.2457  ]
 [166.63461 ]
 [160.90646 ]
 [191.4292  ]]
1140 cost:  29.104013 
prediction
 [[157.08992]
 [183.35974]
 [183.58319]
 [198.82921]
 [139.3618 ]
 [100.32433]
 [148.65405]
 [110.13536]
 [168.7065 ]
 [153.27719]
 [142.73198]
 [137.88347]
 [190.72423]
 [159.75142]
 [148.39468]
 [185.50673]
 [151.79417

1420 cost:  24.068567 
prediction
 [[156.57652]
 [183.5388 ]
 [183.3267 ]
 [198.82625]
 [139.46815]
 [100.92219]
 [148.83946]
 [110.51154]
 [169.39621]
 [154.59816]
 [142.86407]
 [138.471  ]
 [190.19023]
 [158.9658 ]
 [148.73045]
 [185.87831]
 [150.9574 ]
 [179.21094]
 [182.16724]
 [163.33102]
 [174.19753]
 [171.64726]
 [166.71368]
 [159.71571]
 [191.35701]]
1430 cost:  23.910744 
prediction
 [[156.55937]
 [183.54475]
 [183.31812]
 [198.82619]
 [139.47163]
 [100.94216]
 [148.84572]
 [110.52424]
 [169.41925]
 [154.64235]
 [142.8685 ]
 [138.49063]
 [190.17235]
 [158.93947]
 [148.74171]
 [185.89072]
 [150.92932]
 [179.21812]
 [182.14462]
 [163.30959]
 [174.20538]
 [171.6602 ]
 [166.71628]
 [159.6773 ]
 [191.35466]]
1440 cost:  23.754345 
prediction
 [[156.54231 ]
 [183.55067 ]
 [183.30959 ]
 [198.8261  ]
 [139.47513 ]
 [100.962036]
 [148.85196 ]
 [110.53689 ]
 [169.44218 ]
 [154.68633 ]
 [142.87292 ]
 [138.51018 ]
 [190.15456 ]
 [158.91327 ]
 [148.75296 ]
 [185.90309 ]
 [150.90137 ]
 [179

1710 cost:  20.014318 
prediction
 [[156.10992]
 [183.69994]
 [183.09273]
 [198.82433]
 [139.56175]
 [101.46572]
 [149.01149]
 [110.86028]
 [170.02325]
 [155.80247]
 [142.98529]
 [139.00603]
 [189.70224]
 [158.24701]
 [149.0391 ]
 [186.21619]
 [150.18979]
 [179.40984]
 [181.55061]
 [162.74704]
 [174.41295]
 [171.9991 ]
 [166.78575]
 [158.66908]
 [191.29156]]
1720 cost:  19.892193 
prediction
 [[156.09494]
 [183.70511]
 [183.08519]
 [198.82428]
 [139.56473]
 [101.48321]
 [149.01712]
 [110.87163]
 [170.04344]
 [155.84131]
 [142.98923]
 [139.02327]
 [189.68652]
 [158.22382]
 [149.04909]
 [186.22708]
 [150.165  ]
 [179.41637]
 [181.53075]
 [162.72824]
 [174.41994]
 [172.01042]
 [166.78815]
 [158.63536]
 [191.28944]]
1730 cost:  19.771204 
prediction
 [[156.07999]
 [183.71024]
 [183.07767]
 [198.82425]
 [139.56766]
 [101.50061]
 [149.02267]
 [110.88291]
 [170.0635 ]
 [155.87991]
 [142.99312]
 [139.0404 ]
 [189.67084]
 [158.20071]
 [149.05902]
 [186.23785]
 [150.14026]
 [179.42284]
 [181.510

In [17]:
print(sess.run(hypothesis, feed_dict={X:[[100, 70, 101]]}))

[[175.1001]]
