In [13]:
import tensorflow as tf

filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty column. Also specifies the type of the decode result
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size = 10)
    
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
thread = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    c, h, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, 'cost: ', c, '\nprediction\n', h)

0 cost:  46381.477 
prediction
 [[-54.563377]
 [-69.790535]
 [-66.68977 ]
 [-70.587364]
 [-56.122692]
 [-39.03917 ]
 [-48.86518 ]
 [-30.472975]
 [-63.8727  ]
 [-55.24119 ]]
10 cost:  12.772497 
prediction
 [[153.94444]
 [180.8696 ]
 [180.26189]
 [198.36838]
 [135.05423]
 [101.92418]
 [152.45256]
 [118.76317]
 [170.40741]
 [161.77856]]
20 cost:  12.903644 
prediction
 [[155.34642 ]
 [182.56755 ]
 [181.92838 ]
 [200.18173 ]
 [136.35367 ]
 [102.88127 ]
 [153.80396 ]
 [119.756294]
 [171.99533 ]
 [163.24701 ]]
30 cost:  12.877873 
prediction
 [[155.35078]
 [182.58536]
 [181.9396 ]
 [200.19232]
 [136.37172]
 [102.89354]
 [153.80594]
 [119.74907]
 [172.01291]
 [163.26082]]
40 cost:  12.836966 
prediction
 [[155.34575]
 [182.59186]
 [181.93968]
 [200.19078]
 [136.38112]
 [102.89942]
 [153.79884]
 [119.73513]
 [172.0199 ]
 [163.26483]]
50 cost:  12.796175 
prediction
 [[155.34067]
 [182.59825]
 [181.93965]
 [200.18915]
 [136.39043]
 [102.90524]
 [153.7917 ]
 [119.72119]
 [172.02678]
 [163.26875

540 cost:  11.025152 
prediction
 [[155.10693]
 [182.8922 ]
 [181.9393 ]
 [200.11395]
 [136.819  ]
 [103.17235]
 [153.46227]
 [119.07824]
 [172.34312]
 [163.44731]]
550 cost:  10.993283 
prediction
 [[155.10246 ]
 [182.89783 ]
 [181.93929 ]
 [200.1125  ]
 [136.82721 ]
 [103.177444]
 [153.45595 ]
 [119.06592 ]
 [172.34915 ]
 [163.4507  ]]
560 cost:  10.961591 
prediction
 [[155.098  ]
 [182.90343]
 [181.93929]
 [200.11107]
 [136.83539]
 [103.18252]
 [153.44965]
 [119.05362]
 [172.35518]
 [163.45406]]
570 cost:  10.930036 
prediction
 [[155.09357]
 [182.90903]
 [181.93929]
 [200.10963]
 [136.84357]
 [103.18759]
 [153.44336]
 [119.04135]
 [172.36118]
 [163.45743]]
580 cost:  10.898671 
prediction
 [[155.08916]
 [182.91463]
 [181.9393 ]
 [200.10822]
 [136.85172]
 [103.19265]
 [153.4371 ]
 [119.02912]
 [172.36719]
 [163.46078]]
590 cost:  10.867464 
prediction
 [[155.08473]
 [182.92018]
 [181.9393 ]
 [200.10678]
 [136.85982]
 [103.19769]
 [153.43085]
 [119.01692]
 [172.37315]
 [163.46413]]


1030 cost:  9.635515 
prediction
 [[154.90146]
 [183.15158]
 [181.93951]
 [200.04735]
 [137.1976 ]
 [103.4069 ]
 [153.17038]
 [118.50865]
 [172.62097]
 [163.60172]]
1040 cost:  9.610564 
prediction
 [[154.89754]
 [183.15654]
 [181.93954]
 [200.0461 ]
 [137.20485]
 [103.41138]
 [153.16481]
 [118.49773]
 [172.62627]
 [163.60466]]
1050 cost:  9.585653 
prediction
 [[154.89363]
 [183.1615 ]
 [181.93956]
 [200.04483]
 [137.2121 ]
 [103.41584]
 [153.15921]
 [118.48684]
 [172.63158]
 [163.60757]]
1060 cost:  9.560877 
prediction
 [[154.88971]
 [183.16643]
 [181.93956]
 [200.04353]
 [137.2193 ]
 [103.4203 ]
 [153.15364]
 [118.47597]
 [172.63684]
 [163.61047]]
1070 cost:  9.536268 
prediction
 [[154.88583 ]
 [183.17134 ]
 [181.93958 ]
 [200.04228 ]
 [137.22649 ]
 [103.424736]
 [153.14809 ]
 [118.465126]
 [172.6421  ]
 [163.61337 ]]
1080 cost:  9.511736 
prediction
 [[154.88193]
 [183.17625]
 [181.93956]
 [200.041  ]
 [137.23366]
 [103.42918]
 [153.14255]
 [118.45432]
 [172.64734]
 [163.61626]]


1580 cost:  8.4276285 
prediction
 [[154.70015]
 [183.4066 ]
 [181.94028]
 [199.98164]
 [137.57027]
 [103.63645]
 [152.88225]
 [117.9464 ]
 [172.89296]
 [163.75056]]
1590 cost:  8.408511 
prediction
 [[154.69673]
 [183.4109 ]
 [181.94028]
 [199.98051]
 [137.57657]
 [103.64032]
 [152.87735]
 [117.93686]
 [172.89754]
 [163.75304]]
1600 cost:  8.389546 
prediction
 [[154.69336 ]
 [183.41522 ]
 [181.9403  ]
 [199.97943 ]
 [137.58289 ]
 [103.644196]
 [152.87248 ]
 [117.92737 ]
 [172.90213 ]
 [163.75554 ]]
1610 cost:  8.370643 
prediction
 [[154.68996 ]
 [183.4195  ]
 [181.9403  ]
 [199.9783  ]
 [137.58914 ]
 [103.64805 ]
 [152.86761 ]
 [117.917885]
 [172.90668 ]
 [163.75801 ]]
1620 cost:  8.351871 
prediction
 [[154.6866  ]
 [183.42378 ]
 [181.94034 ]
 [199.97722 ]
 [137.5954  ]
 [103.651886]
 [152.86278 ]
 [117.90842 ]
 [172.91124 ]
 [163.76048 ]]
1630 cost:  8.333143 
prediction
 [[154.68324]
 [183.42805]
 [181.94035]
 [199.9761 ]
 [137.60165]
 [103.65572]
 [152.85794]
 [117.89898]
 [172.