In [8]:
import tensorflow as tf

x_data = [
    [1,2,1,1], 
    [2,1,3,2], 
    [3,1,3,4], 
    [4,1,5,5],
    [1,7,5,5],
    [1,2,5,6],
    [1,6,6,6],
    [1,7,7,7]
]

# one-hot encoding
y_data = [
    [0,0,1], #2
    [0,0,1],
    [0,0,1],
    [0,1,0], #1
    [0,1,0],
    [0,1,0],
    [1,0,0], #0
    [1,0,0]
]

X = tf.placeholder(tf.float32, [None, 4])
Y = tf.placeholder(tf.float32, [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_mean(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
            
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))
    
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9],
                                              [1, 3,  4, 3],
                                              [1, 1,  0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 4.691019
200 0.56557715
400 0.4592135
600 0.3640802
800 0.27393532
1000 0.23230219
1200 0.2108104
1400 0.19286698
1600 0.17765269
1800 0.16459174
2000 0.15326208
[[9.8812804e-03 9.9011046e-01 8.2914275e-06]] [1]
[[9.8812804e-03 9.9011046e-01 8.2914275e-06]
 [7.9919809e-01 1.8346715e-01 1.7334705e-02]
 [8.6370058e-09 3.1153968e-04 9.9968851e-01]] [1 0 2]
